### ISSUE TITLE
[UI] [Dashboard] Create + Edit My Token

### ISSUE THREAD

**Issue by proofoftom** [raid-guild/gitcoinco-web#1]
Create + Manage a personal token at the top of the Personal Token Dashboard tab

### User Story

As a Gitcoin user, I want to create a personal token so that I can sell my time and services.

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Gitcoin is in a unique position to give users an easy way to raise capital today for work tomorrow through a personal token representing an hour of time.

### Description
[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

- Add a section to the Personal Token Dashboard for users to mint a new token, set the price of that token and later return to mint more tokens or adjust the price of the token.
- Display a CTA for those who have not created a personal token with a link to Quickstart > Maker a Token.
- Display Token Name, Symbol, Price and Supply while only letting users adjust the Price and Supply when selecting "Edit"
- On top of storing data onchain, this data should be persisted in the database.

[comment]: # (Describe what you expected to happen.)

### Definition of Done

See mockup of Dashboard flow

[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information

See Dashboard - specifically the top section featuring both the Create and Edit sections: https://www.figma.com/file/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=136%3A77

**Comment by coopahtroopanew** [comment]
Updated description. Reference this Prototype and select "Create" for how it works in practice. Please note that after creating the token, the dashboard will update with the new token details where the Create CTA used to be. https://www.figma.com/proto/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=260%3A1570&scaling=min-zoom

**Comment by cupOJoseph** [comment]
Please also include:
- Gitcoin's Standard _Waiting on transaction_ modal
- transaction confirmed acknowledgement
- transaction failed acknowledgement and handling
