### ISSUE TITLE
[UI] [Profile] Buyer View

### ISSUE THREAD

**Issue by proofoftom** [raid-guild/gitcoinco-web#11]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

**THIS TASK IS FOR CREATOR THE BUYER VIEW OF A PROFILE AS IT RELATES TO PERSONAL TOKENS**

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Those looking to interact with personal tokens can buy and redeem them directly through another users Profile.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Feature

Add a new profile component in the Profile page next to "Funder Rank" 
Displays Price, Total Supply, Number of times redeemed and Holders.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Designed initial concept for Profile tab
- Updated design with comments from Gitcoin team
- Synthesized "Buy" and "Reedem" flow including separate tasks under [UI] [Profile] for each modal.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

See Profile Widget > Buyer View https://www.figma.com/file/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=131%3A0

**Comment by zoek1** [comment]
@coopahtroopanew could i take this?

**Comment by coopahtroopanew** [comment]
Data from WIP Issue needs to be updated with real data from the database
