### ISSUE TITLE
[UI] [Profile] Creator View

### ISSUE THREAD

**Issue by proofoftom** [raid-guild/gitcoinco-web#12]
### User Story

**THIS TASK IS FOR THE PROFILE PAGE AND WHAT A CREATOR SEES WHEN VIEWING THEIR OWN PROFILE WITH RESPECT TO PERSONAL TOKENS**

As a Gitcoin User, I want to Create a Personal Token so that I can borrow against my reputation.

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Allow users to mint their own personal token - redeemable for an hour of their time directly through Gitcoin. 

We will first guide them to the "Make a Token" Education FAQ prior to sending them to the Dashboard to actually create the token.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Clickthrough Button

### Definition of Done

- Created design mockup for starting creation process on a users profile
- Created design mockup for "Make a Token" quickstart page.
- Created design mockup for minting tokens and adjusting price in Personal Token Dashboard
- Updated flow in Figma to illustrate end-to-end experience

[comment]: # (Any other information that would be useful, bullets are helpful.)

### Additional Information

See Quickstart > Make a Token  along with [Prototype] Profile - Creator View https://www.figma.com/file/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=136%3A77
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by cupOJoseph** [comment]
left design is when a user has not created their token yet. Right if they have, and they can not change the greyed out options.

Included in this will need to be a global var/ db read/write for if a user has launched their personal token yet. And then update the details associated with each user 

in db there should be new col for each user's:
- ptoken_address
- hasLaunchedpToken
- tokenName
- tokenSymbol (must be <5 chars)
- TokenDAIPrice
- totalMintedTokens

**Comment by proofoftom** [comment]
Sorry I didn't catch this last night. A couple things here, I already implemented the Personal Token tab in #18 which is deprecated because there's no longer a Personal Token tab in the user settings page. All of that is handled in the dashboard now.

A note to the database schema: I think a lot, if not all of the information will be on chain. Not sure we need to redundantly add it to the database. Can be convinced otherwise though.

**Comment by coopahtroopanew** [comment]
Updated task - Only change is that Make a Token directs users to the DASHBOARD instead of Settings

**Comment by coopahtroopanew** [comment]
Created a prototype in Figma to illustrate the flow: https://www.figma.com/proto/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=338%3A1042&scaling=min-zoom

**Comment by iamonuwa** [comment]
Jumping on this immediately
