### ISSUE TITLE
[UI] [Users] Personal Token Filter

### ISSUE THREAD

**Issue by proofoftom** [raid-guild/gitcoinco-web#13]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a Gitcoin user, I want to see which users have personal tokens so that I can redeem an hour of their time.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: A personal token filter allows users to quickly search for which other users have tokens which can be redeemed for time - especially when paired by sorting with tags like Solidity, CSS, etc.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Filter - Add a new filter tab to the /user search bar which sorts according to whether or not that person has created a personal token.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Mock up of where the personal token box would live.

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

See Token Sorting: https://www.figma.com/file/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=159%3A917

**Comment by zoek1** [comment]
I could help on this @jschiarizzi

**Comment by coopahtroopanew** [comment]
Having Victor work on this task
