### ISSUE TITLE
[UI] [Dashboard] In Progress Request (Incoming + Outgoing)

### ISSUE THREAD

**Issue by coopahtroopanew** [raid-guild/gitcoinco-web#15]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a personal token user, I want to track my incoming and outgoing redemptions.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: The In Progress Redemptions section of the Token tab allows users to manage their incoming and outgoing token requests.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Section in Dashboard

Modify "In Progress" section of Token dashboard to accommodate incoming and outgoing requests.
Allow Create to Accept or Deny incoming requests
Allow Buyer to mark outgoing requests as Complete
Make it so that tokens are transferred out of a Buyer's wallet when they mark a redemption as Finalized.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- New design drafted

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

See Dashboard for flow https://www.figma.com/file/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=135%3A0

**Comment by coopahtroopanew** [comment]
Changed button text for outgoing request from "Finalize" to "Complete"

**Comment by cupOJoseph** [comment]
Please also include:
- Gitcoin's Standard _Waiting on transaction_ modal
- transaction confirmed acknowledgement
- transaction failed acknowledgement and handling

**Comment by coopahtroopanew** [comment]
Hey @proofoftom @iamonuwa can we please mimic [the default Dashboard info screen](https://gitcoin.co/dashboard) for when no requests are currently in progress?

Here's what it looks like. 

<img width="856" alt="Screen Shot 2020-06-02 at 1 05 26 PM" src="https://user-images.githubusercontent.com/59624339/83548554-f2644880-a4d1-11ea-8cfa-275184d0877c.png">

I've also attached the Gitcoin Personal Token logo to be substituted for the Robot.

![Personal Token Logo](https://user-images.githubusercontent.com/59624339/83548575-f8f2c000-a4d1-11ea-9227-f444df634a6b.png)

**Comment by iamonuwa** [comment]
Absolutely. Will be ready tomorrow morning

**Comment by iamonuwa** [comment]
Done
