### ISSUE TITLE
[UI] [Quickstart] Make a Token

### ISSUE THREAD

**Issue by coopahtroopanew** [raid-guild/gitcoinco-web#17]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As a Creator of personal tokens, I want to learn more about why I should make a token so that I can understand how they work.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: This page is educational content to help users understand how personal tokens work and where to create them (Dashboard > Create a Personal Token)

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Page

Create gitcoin.com/token/quickstart/create
Populate with educational content provided below
Link to Personal Token tab in the Dashboard where Creators can make a personal token
Ensure this page is linked to [Profile] Creator View button "Create A Token"

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

- Design drafted
- Content provided

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Content: https://docs.google.com/document/d/1TENg-jNbXLJplfacV_6sjNPdZtSuYkyWCVUbd3f6_eQ/edit?usp=sharing
Design: See Quickstart > Make a Token: https://www.figma.com/file/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=168%3A47

**Comment by coopahtroopanew** [comment]
Updated description to match the new flow directing uses to the Personal Token tab in the dashboard. See this prototype for how it works in practice: https://www.figma.com/proto/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=338%3A847&scaling=min-zoom

**Comment by coopahtroopanew** [comment]
@iamonuwa please see comments for quick updates:

- Switch "Buy a Token" and "Make a Token" so that "Make a Token" comes first.

- Center the CTA (What are you waiting for?) and the "Get Started" button and add a line before the Disclaimer: "Have any questions? [BREAK] Reach out to a Gitcoin Core Team member on Slack"

- Note that there are separate FAQs for "Buy" and "Make" which you can see in the document here. I've [updated the text](https://docs.google.com/document/d/1TENg-jNbXLJplfacV_6sjNPdZtSuYkyWCVUbd3f6_eQ/edit?usp=sharing) on a few of the questions + answers and added comments next to the ones which need revising so you can clearly see what needs to be updated.

- Make sure the formatting matches that of the [Grants Quickstart](https://gitcoin.co/grants/quickstart)

**Comment by dekanbro** [comment]
is this the same as #16 ?

**Comment by coopahtroopanew** [comment]
It's a different piece of Quickstart. Basically one of the two tabs in Quickstart. However the bulk of this has already been done by @iamonuwa - Just needs to be updated with my last comments regarding the formatting and FAQ content

**Comment by dekanbro** [comment]
ok, i think i got this in PR #25
