### ISSUE TITLE
[UI] [Profile| Buy a Token Modal

### ISSUE THREAD

**Issue by proofoftom** [raid-guild/gitcoinco-web#2]
### User Story

As a Gitcoin Buyer, I want to purchase someone's personal token so that I can redeem an hour of their time.

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Allow Buyers to purchase a personal token from a Creator to redeem their time.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Modal

Create a modal which allows users to buy personal tokens when selecting the "Buy" button on a user's personal token section of the Profile.

### Expected Behavior

[comment]: # (Describe what you expected to happen.)

We expect users to find those with personal tokens on the /user page and purchase their tokens directly through their Gitcoin Profile.

### Definition of Done

[comment]: # (Any other information that would be useful, bullets are helpful.)

- Refined /buy page to a modal on the profile instead of creating a standalone page.
- Created mockup which synthesized purchase process in line with Gitcoin team comments

### Additional Information

[comment]: # (Any other information that would be useful, content, screenshots, etc.)

See "Buy/Redeem Modal" and focus on the "Buy" frame. See [Protoype] Profile - Buyer View for how it looks in practice https://www.figma.com/file/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=159%3A917

**Comment by coopahtroopanew** [comment]
Created a prototype illustrating the flow as a Buyer: https://www.figma.com/proto/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=346%3A0&scaling=min-zoom

**Comment by cupOJoseph** [comment]
Please also include:
- Gitcoin's Standard _Waiting on transaction_ modal
- transaction confirmed acknowledgement
- transaction failed acknowledgement and handling
