### ISSUE TITLE
[UI] [Dashboard] Completed Section

### ISSUE THREAD

**Issue by proofoftom** [raid-guild/gitcoinco-web#4]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

I want to track my completed personal token requests.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: Users will field, accept and finalizee incoming and outgoing requests directly via their Dashboard under the "Personal Token" tab.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Section

Modify the Completed section of dashboard
Move finalized redemptions from "In Progress" to "Completed"

**Note: Buyer is responsible for FINALIZING outgoing requests. Once finalized by the buyer, it will be displayed as a Completed outgoing request for the buyer and as a Completed incoming request for the Creaor.**

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

Design specs provided via Figma

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

See Dashboard Prototype and focus on the "Finalize" Prompt: https://www.figma.com/proto/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=260%3A1570&scaling=min-zoom

**Comment by coopahtroopanew** [comment]
Updated task content to illustrate new Dashboard flow. Prototype to play with here https://www.figma.com/proto/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=260%3A1570&scaling=min-zoom
