### ISSUE TITLE
[UI] [Quickstart] Home

### ISSUE THREAD

**Issue by proofoftom** [raid-guild/gitcoinco-web#8]
### User Story

[comment]: # (As a <user type>, I want to <task> so that <goal>.)

As someone interested in the idea of personal tokens, I want to learn more about them so that I may interact with them on the Gticoin platform.

### Why Is this Needed

[comment]: # (Describe the problem and why this task is needed. Provide description of the current state, what you would like to happen, and what actually happen)
*Summary*: While many of us are familiar with the term "personal token", having quickstart page which describes the "why" and "how" for both buying and selling personal tokens is a great place to point beginners.

### Description

[comment]: # (Feature or Bug? i.e Type: Bug)
*Type*: Page

Create gitcoin.co/token/quickstart and populate with information from the "Quickstart Home" content on Figma.

### Definition of Done
[comment]: # (Any other information that would be useful, bullets are helpful.)

Content Drafted (see below)
Design Drafted (Figma)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

Content for Quickstart Home: https://docs.google.com/document/d/1TENg-jNbXLJplfacV_6sjNPdZtSuYkyWCVUbd3f6_eQ/edit?usp=sharing

See Quickstart > Quickstart Home https://www.figma.com/file/3kFR9QQTEQRytJg5uKs5Zg/Gitcoin-Personal-Tokens?node-id=168%3A1

**Comment by coopahtroopanew** [comment]
@iamonuwa under FAQ "Buy a Token" please revise the answer to "What happens to my personal tokens when they are used" to the following:

When a Creator accepts your request, you are responsible for marking it as complete. Upon marking a request as complete, you will be prompted to complete a transaction that sends the amount of personal tokens used back to the Creator's sale contract.

**Comment by coopahtroopanew** [comment]
@iamonuwa Please switch "Buy a Token" and "Make a Token" so that "Make a Token" comes first.

Please note that there are separate FAQs for "Buy" and "Make" which you can see in the document here. I've [updated the text](https://docs.google.com/document/d/1TENg-jNbXLJplfacV_6sjNPdZtSuYkyWCVUbd3f6_eQ/edit?usp=sharing) on a few of these and added a comment so you can clearly see what needs to be updated.

Please make sure the formatting matches that of the [Grants Quickstart](https://gitcoin.co/grants/quickstart)

**Comment by coopahtroopanew** [comment]
@iamonuwa Please remove the top "Learn about Personal Token" tab. There does not need to be a tab as there is only one section. If a tab is necessary, please either hide it or change the text to "Introduction" if it can not be hidden
